/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;
import Entidades.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class Formulario extends javax.swing.JFrame {
    private double e ;
    private ArrayList<Recinto> Lista_Recintos;
    private ArrayList<Relacion> Lista_Relaciones;
    private ArrayList<Double> Lista_Donaciones;
    DefaultTableModel TablaModelo;
    DefaultTableModel TablaModelo1;
    DefaultTableModel TablaModelo2;
    DefaultTableModel TablaModelo3;
    DefaultTableModel TablaModelo4;
    DecimalFormat df = new DecimalFormat("#.00");
    double total;

    
    public Formulario() {
        initComponents();
        this.TablaModelo  = (DefaultTableModel)this.jTableDatos.getModel();
        this.TablaModelo1 = (DefaultTableModel)this.jTable1.getModel();
        this.TablaModelo2 = (DefaultTableModel)this.jTable2.getModel();
        this.TablaModelo3 = (DefaultTableModel)this.jTable3.getModel();
        this.TablaModelo4 = (DefaultTableModel)this.jTable4.getModel();
        this.Lista_Recintos = new ArrayList<>();
        this.Lista_Relaciones = new ArrayList<>();
        this.Lista_Donaciones = new ArrayList<>();
        this.Simulación();
        this.CargarSucur();
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtApellidoD = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTNombreD = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jtDuiD = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTApellidoE = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jtDuiE = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTNombreE = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jtmonto = new javax.swing.JFormattedTextField();
        ComboBoxRecinto = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        JBDonar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jtmin = new javax.swing.JFormattedTextField();
        jtmax = new javax.swing.JFormattedTextField();
        jtprom = new javax.swing.JFormattedTextField();
        jttotal = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        BotonBusqueda = new javax.swing.JButton();
        BusquedaCodigo = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        BusDesd = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        BusqHast = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        BuscarxPrecio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel1.setText("CDSV");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 12)); // NOI18N
        jLabel2.setText("Centro de donación salvadoreño");

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setText("DONADOR");

        jLabel4.setText("Nombre");

        jtApellidoD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jtApellidoD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtApellidoDKeyTyped(evt);
            }
        });

        jLabel5.setText("Apellido");

        jTNombreD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jTNombreD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreDKeyTyped(evt);
            }
        });

        jLabel6.setText("DUI");

        jtDuiD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        try {
            jtDuiD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtDuiD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDuiDKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel8.setText("Persona Encargada");

        jLabel9.setText("Nombre");

        jTApellidoE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jTApellidoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTApellidoEKeyTyped(evt);
            }
        });

        jLabel10.setText("Apellido");

        jtDuiE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        try {
            jtDuiE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtDuiE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDuiEKeyTyped(evt);
            }
        });

        jLabel11.setText("DUI");

        jTNombreE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jTNombreE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreEKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel12.setText("DONATIVO");

        jLabel14.setText("Cantidad");

        jLabel15.setText("Nombre de los recintos");

        jLabel16.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel16.setText("¿A quienes quieres ayudar?");

        jtmonto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jtmonto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######"))));

        ComboBoxRecinto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxRecintoItemStateChanged(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Estadisticas de las donaciones");

        jLabel18.setText("MIN. $");

        jLabel19.setText("MAX. $");

        jLabel20.setText("Donaciones totales. $");

        jLabel21.setText("Prom. $");

        JBDonar.setText("¡DONAR!");
        JBDonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDonarActionPerformed(evt);
            }
        });

        jLabel13.setText("Codigo de validación");

        jTCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        try {
            jTCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCodigoKeyTyped(evt);
            }
        });

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donador", "Persona Encargada", "Codido", "Cantidad", "Nombre del Recinto", "Recinto"
            }
        ));
        jScrollPane1.setViewportView(jTableDatos);

        jtmin.setEditable(false);
        jtmin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jtmax.setEditable(false);

        jtprom.setEditable(false);

        jttotal.setEditable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Donación"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Donación"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Donación"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Donación"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jLabel22.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("Cuartil 1");

        jLabel23.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Cuartil 2");

        jLabel24.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 255, 51));
        jLabel24.setText("Cuartil 3 ");

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 0, 153));
        jLabel25.setText("Cuartil 4");

        jLabel28.setText("5 dig.");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel30.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel30.setText("Buscar por codigo");

        BotonBusqueda.setText("Iniciar Busqueda");
        BotonBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBusquedaActionPerformed(evt);
            }
        });

        try {
            BusquedaCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel26.setText("5 Dig.");

        jLabel29.setText("Desde $");

        jLabel31.setText("Hasta $");

        jLabel32.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel32.setText("Busqueda por Donativo");

        BuscarxPrecio.setText("Iniciar Busqueda");
        BuscarxPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarxPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BuscarxPrecio)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BusquedaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BusDesd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BusqHast, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel32)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusquedaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addComponent(BotonBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel32)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusDesd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31)
                    .addComponent(BusqHast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BuscarxPrecio)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtDuiD, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtDuiE, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel13))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(jtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel28))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel12)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(JBDonar)
                                        .addGap(27, 27, 27)
                                        .addComponent(ComboBoxRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(426, 426, 426)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(174, 174, 174)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel18))
                                    .addComponent(jLabel20))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtprom)
                                            .addComponent(jtmax, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel22))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jtDuiD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtDuiE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addGap(1481, 1481, 1481))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jtmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jtmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtprom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBoxRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBDonar))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1084, 1084, 1084))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addComponent(jLabel7)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreDKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) 
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null,"Favor digite solo letras", "WARNING", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_jTNombreDKeyTyped

    private void jtApellidoDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApellidoDKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) 
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null,"Favor digite solo letras", "WARNING", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_jtApellidoDKeyTyped

    private void jtDuiDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDuiDKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) 
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Favor digite solo números", "WARNING", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_jtDuiDKeyTyped

    private void jTNombreEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreEKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) 
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null,"Favor digite solo letras", "WARNING", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_jTNombreEKeyTyped

    private void jTApellidoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTApellidoEKeyTyped
       char c = evt.getKeyChar();
        if (Character.isDigit(c)) 
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null,"Favor digite solo letras", "WARNING", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_jTApellidoEKeyTyped

    private void jtDuiEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDuiEKeyTyped
       char c = evt.getKeyChar();
        if (Character.isLetter(c)) 
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Favor digite solo números", "WARNING", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_jtDuiEKeyTyped

    private void jTCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCodigoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) 
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Favor digite solo números", "WARNING", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_jTCodigoKeyTyped

    private void JBDonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDonarActionPerformed
              this.Lista_Relaciones.add(new Relacion(
                new Personas(this.jTNombreD.getText().trim(), 
                             this.jtApellidoD.getText().trim(),
                             this.jtDuiD.getText().trim()), 
                new Personas(this.jTNombreE.getText().trim(),
                             this.jTApellidoE.getText().trim(), 
                             this.jtDuiE.getText().trim()), 
                this.Lista_Recintos.get(this.ComboBoxRecinto.getSelectedIndex()), 
                new Donativo(this.jTCodigo.getText().trim(),
                        new Date(),
                        Double.parseDouble(this.jtmonto.getText())),
                this.Lista_Recintos.get(this.ComboBoxRecinto.getSelectedIndex()).getLista_Recintos().get(this.jComboBox1.getSelectedIndex())));  
        this.CargarTabla();
        this.jtmin.setText(Double.toString(this.minimo()));
        this.jtmax.setText(Double.toString(this.maximo()));
        this.jtprom.setText(Double.toString(this.Promedio()));
        this.jttotal.setText(Double.toString(this.Total()));
        this.Lista_Donaciones.add(Double.parseDouble(this.jtmonto.getText()));
        //this.CargarTabla();
      
//        this.agregarTablaSegundoCuartil();
//        this.agregarTablaTercerCuartil();
//        this.agregarTablaCuartoCuartil();
        this.Limpieza();
        this.CargarCuartiles();
    }//GEN-LAST:event_JBDonarActionPerformed

    private void ComboBoxRecintoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxRecintoItemStateChanged
       this.CargarRecintos(this.ComboBoxRecinto.getSelectedIndex());
    }//GEN-LAST:event_ComboBoxRecintoItemStateChanged

    private void BotonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBusquedaActionPerformed
        this.TablaModelo.setRowCount(0);
        String CodigoBusqueda = this.BusquedaCodigo.getText();
        Boolean recorrer = true;
        int contador = -1;
        this.TablaModelo.getDataVector().removeAllElements();
        this.BusquedaCodigo.setText("");
        while(recorrer)
        {
            contador++;
            if (this.Lista_Relaciones.get(contador).getDonativoD().getCodigoValidez().equals(CodigoBusqueda)) {
                recorrer = false;
            }
            String[] registro = {
                this.Lista_Relaciones.get(contador).getDonador().getPersonas()+ " "+ this.Lista_Relaciones.get(contador).getDonador().getApellido(),
                this.Lista_Relaciones.get(contador).getEncargadoD().getPersonas()+" "+ this.Lista_Relaciones.get(contador).getEncargadoD().getApellido(),
                this.Lista_Relaciones.get(contador).getDonativoD().getCodigoValidez(),
                Double.toString(this.Lista_Relaciones.get(contador).getDonativoD().getCantidad()),
                this.Lista_Relaciones.get(contador).getTipoRecintos().getPersonas()+" "+ this.Lista_Relaciones.get(contador).getTipoRecintos().getApellido(),
                this.Lista_Relaciones.get(contador).getRecintoD().getNombreRecinto()};
            this.TablaModelo.getDataVector().removeAllElements();
            this.TablaModelo.addRow(registro);
        }
    }//GEN-LAST:event_BotonBusquedaActionPerformed

    private void BuscarxPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarxPrecioActionPerformed
        this.TablaModelo.setRowCount(0);
        double limSup = Double.parseDouble(this.BusqHast.getText());
        double limInf = Double.parseDouble(this.BusDesd.getText());
        this.BusDesd.setText("");
        this.BusqHast.setText("");
        for (int i = 0; i < this.Lista_Relaciones.size(); i++) 
        {
            if (this.Lista_Relaciones.get(i).getDonativoD().getCantidad() <= limSup && this.Lista_Relaciones.get(i).getDonativoD().getCantidad()>=limInf) 
            {
                String[] datos = {
                this.Lista_Relaciones.get(i).getDonador().getPersonas()+ " "+ this.Lista_Relaciones.get(i).getDonador().getApellido(),
                this.Lista_Relaciones.get(i).getEncargadoD().getPersonas()+" "+ this.Lista_Relaciones.get(i).getEncargadoD().getApellido(),
                this.Lista_Relaciones.get(i).getDonativoD().getCodigoValidez(),
                Double.toString(this.Lista_Relaciones.get(i).getDonativoD().getCantidad()),
                this.Lista_Relaciones.get(i).getTipoRecintos().getPersonas()+" "+ this.Lista_Relaciones.get(i).getTipoRecintos().getApellido(),
                this.Lista_Relaciones.get(i).getRecintoD().getNombreRecinto()};
                this.TablaModelo.addRow(datos);
                
                
            }
            
            
        }
        
    }//GEN-LAST:event_BuscarxPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBusqueda;
    private javax.swing.JTextField BusDesd;
    private javax.swing.JButton BuscarxPrecio;
    private javax.swing.JTextField BusqHast;
    private javax.swing.JFormattedTextField BusquedaCodigo;
    private javax.swing.JComboBox<String> ComboBoxRecinto;
    private javax.swing.JButton JBDonar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JFormattedTextField jTApellidoE;
    private javax.swing.JFormattedTextField jTCodigo;
    private javax.swing.JFormattedTextField jTNombreD;
    private javax.swing.JFormattedTextField jTNombreE;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JFormattedTextField jtApellidoD;
    private javax.swing.JFormattedTextField jtDuiD;
    private javax.swing.JFormattedTextField jtDuiE;
    private javax.swing.JFormattedTextField jtmax;
    private javax.swing.JFormattedTextField jtmin;
    private javax.swing.JFormattedTextField jtmonto;
    private javax.swing.JFormattedTextField jtprom;
    private javax.swing.JFormattedTextField jttotal;
    // End of variables declaration//GEN-END:variables

    private void Simulación() {
        this.Lista_Recintos.add(new Recinto("Asilo", "Santa Ana",
                new Personas("Juan", "Lopez ", "1234 "), 
                new ArrayList<>()));
        this.Lista_Recintos.get(0).getLista_Recintos().add(new Personas("Manos de Dios", " ", " "));
        this.Lista_Recintos.get(0).getLista_Recintos().add(new Personas("Bendicion de Dios", " ", " "));
        this.Lista_Recintos.get(0).getLista_Recintos().add(new Personas("Centenar", " ", " "));
        
        this.Lista_Recintos.add(new Recinto("Perrera", "Santa Ana",
                new Personas("Adonay", "Valenvia", "1234"),
                new ArrayList<>()));
        this.Lista_Recintos.get(1).getLista_Recintos().add(new Personas("Huellitas", " ", " "));
        this.Lista_Recintos.get(1).getLista_Recintos().add(new Personas("El mejor amigo", " ", " "));
        this.Lista_Recintos.get(1).getLista_Recintos().add(new Personas("Machon", " ", " "));
        
        this.Lista_Recintos.add(new Recinto("Hospital", "Santa Ana",
                new Personas("Dr Luis", "Lemus", "1234"),
                new ArrayList<>()));
        this.Lista_Recintos.get(2).getLista_Recintos().add(new Personas("Hospital Cader", " ", " "));
        this.Lista_Recintos.get(2).getLista_Recintos().add(new Personas("ISSS ", " ", " "));
        this.Lista_Recintos.get(2).getLista_Recintos().add(new Personas("San Juan de Dios", " ", " "));       
    }

  

    private void CargarTabla() 
    {
        this.TablaModelo.getDataVector().removeAllElements();
        for (int j = 0; j < this.Lista_Relaciones.size(); j++) 
        {
            String[] registro = {
                this.Lista_Relaciones.get(j).getDonador().getPersonas()+ " "+ this.Lista_Relaciones.get(j).getDonador().getApellido(),
                this.Lista_Relaciones.get(j).getEncargadoD().getPersonas()+" "+ this.Lista_Relaciones.get(j).getEncargadoD().getApellido(),
                this.Lista_Relaciones.get(j).getDonativoD().getCodigoValidez(),
                Double.toString(this.Lista_Relaciones.get(j).getDonativoD().getCantidad()),
                this.Lista_Relaciones.get(j).getTipoRecintos().getPersonas()+" "+ this.Lista_Relaciones.get(j).getTipoRecintos().getApellido(),
                this.Lista_Relaciones.get(j).getRecintoD().getNombreRecinto()};
            this.TablaModelo.addRow(registro);
        }
       
    }

    private double minimo() {
        double min = 0;
        if (this.Lista_Relaciones.size()>0) 
        {
            min = this .Lista_Relaciones.get(0).getDonativoD().getCantidad();
            for (int i = 1; i <this.Lista_Relaciones.size(); i++) 
            {
                if (min > this.Lista_Relaciones.get(i).getDonativoD().getCantidad())
                    min = this.Lista_Relaciones.get(i).getDonativoD().getCantidad();    
            }
        }
        return min;
    }

    private double maximo() {
       double max = 0;
        if (this.Lista_Relaciones.size()>0) 
        {
            max = this.Lista_Relaciones.get(0).getDonativoD().getCantidad();
            for (int i = 0; i < this.Lista_Relaciones.size(); i++) 
            {
                if (max < this.Lista_Relaciones.get(i).getDonativoD().getCantidad()) 
                    max =this.Lista_Relaciones.get(i).getDonativoD().getCantidad();
            }
        }
        return max;
    }

    private double Promedio() 
    {
        double prom = (this.Total()/this.Lista_Relaciones.size());
        prom*=100;
        prom = Math.round(prom);
        return (prom/100);
        
        
    }

    private double Total() {
       double total = 0;
        for (int i = 0; i < this.Lista_Relaciones.size(); i++) 
        {
            total += this.Lista_Relaciones.get(i).getDonativoD().getCantidad();
        }
        total*= 100;
        total = Math.round(total);
        return (total/100);
    }

     private void CargarSucur() 
    {
        this.ComboBoxRecinto.removeAllItems();
        for (int i = 0; i < this.Lista_Recintos.size(); i++) 
        {
            this.ComboBoxRecinto.addItem(this.Lista_Recintos.get(i).getNombreRecinto());
            
        }
    }
    private void CargarRecintos(int idRecin)
    {
        this.jComboBox1.removeAllItems();
        for (int i = 0; i <this.Lista_Recintos.get(idRecin).getLista_Recintos().size(); i++) 
        {
            this.jComboBox1.addItem(this.Lista_Recintos.get(idRecin).getLista_Recintos().get(i).getPersonas()+" "+
                    this.Lista_Recintos.get(idRecin).getLista_Recintos().get(i).getApellido());
            
        }
        
    
    
    }
    private void Limpieza()
    {
        this.jTNombreD.setText("");
        this.jTNombreE.setText("");
        this.jtApellidoD.setText("");
        this.jTApellidoE.setText("");
        this.jtmonto.setText("");
        this.jTCodigo.setText("");
        this.jtDuiE.setText("");
        this.jtDuiD.setText("");
        
    }
    private double Cuartil1 ()
    {
        double limite = maximo();
        limite *= 0.25;
        limite *=100;
        limite = Math.round(limite);
        return (limite/100);
    }
    private double Cuartil2()
    {
        double limite = maximo();
        limite *= 0.50;
        limite *=100;
        limite = Math.round(limite);
        return (limite/100);
    }
    private double Cuartil3()
    {
        double limite = maximo();
        limite *= 0.75;
        limite *=100;
        limite = Math.round(limite);
        return (limite/100);
    }
    private void CargarCuartiles()
    {
        this.TablaModelo1.getDataVector().removeAllElements();
        this.TablaModelo2.getDataVector().removeAllElements();
        this.TablaModelo3.getDataVector().removeAllElements();
        this.TablaModelo4.getDataVector().removeAllElements();
        for (int i = 0; i < this.Lista_Relaciones.size(); i++) 
        {
            if (this.Lista_Relaciones.get(i).getDonativoD().getCantidad()<= Cuartil1())
            {
                String [] Registro = {this.Lista_Relaciones.get(i).getDonador().getPersonas(),Double.toString(this.Lista_Relaciones.get(i).getDonativoD().getCantidad())};
                this.TablaModelo1.addRow(Registro);
            }
            if (this.Lista_Relaciones.get(i).getDonativoD().getCantidad()>Cuartil1()&& Lista_Relaciones.get(i).getDonativoD().getCantidad() <=Cuartil2()) 
            {
                String [] Registro = {this.Lista_Relaciones.get(i).getDonador().getPersonas(),Double.toString(this.Lista_Relaciones.get(i).getDonativoD().getCantidad())};
                this.TablaModelo2.addRow(Registro);
            }
            if (this.Lista_Relaciones.get(i).getDonativoD().getCantidad()>Cuartil2() &&Lista_Relaciones.get(i).getDonativoD().getCantidad()<=Cuartil3()) 
            {
                String [] Registro = {this.Lista_Relaciones.get(i).getDonador().getPersonas(),Double.toString(this.Lista_Relaciones.get(i).getDonativoD().getCantidad())};
                this.TablaModelo3.addRow(Registro);
            }
            if (this.Lista_Relaciones.get(i).getDonativoD().getCantidad()>Cuartil3()) 
            {
                String [] Registro = {this.Lista_Relaciones.get(i).getDonador().getPersonas(),Double.toString(this.Lista_Relaciones.get(i).getDonativoD().getCantidad())};
                this.TablaModelo4.addRow(Registro);
                
            }
        }
    
    }
   
    
}
